// <auto-generated />
using System;
using ExamenSegundaUnidad.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenSegundaUnidad.Migrations
{
    [DbContext(typeof(ProjectServiceDbContext))]
    [Migration("20240727122107_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.AmortizationDataEntity", b =>
                {
                    b.Property<Guid>("AmortizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("amortization_id");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("days");

                    b.Property<double>("Installment")
                        .HasColumnType("float")
                        .HasColumnName("installment");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<double>("Interest")
                        .HasColumnType("float")
                        .HasColumnName("interes_date");

                    b.Property<double>("LifeInsuranceOverDebt")
                        .HasColumnType("float")
                        .HasColumnName("life_insurace");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<double>("LvPaymentNoLinsurance")
                        .HasColumnType("float")
                        .HasColumnName("lv_payment_no_LfIns");

                    b.Property<double>("LvPayment_Linsurance")
                        .HasColumnType("float")
                        .HasColumnName("lv_payment_LfIns");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<double>("PrincipalBalance")
                        .HasColumnType("float")
                        .HasColumnName("principal_balance");

                    b.HasKey("AmortizationId");

                    b.HasIndex("LoanId");

                    b.ToTable("amortization", "dbo");
                });

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.ProspectsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_name");

                    b.Property<int>("Commission")
                        .HasColumnType("int")
                        .HasColumnName("commision");

                    b.Property<DateTime>("DisbursmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("disbursment_date");

                    b.Property<DateTime>("FirstPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<int>("Identity_Number")
                        .HasColumnType("int")
                        .HasColumnName("identity_number");

                    b.Property<int>("InterestRate")
                        .HasColumnType("int")
                        .HasColumnName("interes_rate");

                    b.Property<double>("LoanAmount")
                        .HasColumnType("float")
                        .HasColumnName("loan_amount");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<int>("Term")
                        .HasColumnType("int")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.ToTable("prospects", "dbo");
                });

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.AmortizationDataEntity", b =>
                {
                    b.HasOne("ExamenSegundaUnidad.Database.Entity.ProspectsEntity", "LoanIdentification")
                        .WithMany("AmortizationDataEntities")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanIdentification");
                });

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.ProspectsEntity", b =>
                {
                    b.Navigation("AmortizationDataEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
