// <auto-generated />
using System;
using ExamenSegundaUnidad.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenSegundaUnidad.Migrations
{
    [DbContext(typeof(ProjectServiceDbContext))]
    [Migration("20240727011622_iniy")]
    partial class iniy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.AmortizationDataEntity", b =>
                {
                    b.Property<Guid>("AmortizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("amortization_id");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("days");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<double>("Interest")
                        .HasColumnType("float")
                        .HasColumnName("interes_date");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<double>("LvPaymentNoSVSD")
                        .HasColumnType("float")
                        .HasColumnName("lv_payment_no_Svds");

                    b.Property<double>("LvPaymentSVSD")
                        .HasColumnType("float")
                        .HasColumnName("lv_payment_Svds");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<double>("PrincipalBalance")
                        .HasColumnType("float")
                        .HasColumnName("principal_balance");

                    b.HasKey("AmortizationId");

                    b.HasIndex("LoanId");

                    b.ToTable("amortization", "dbo");
                });

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.LoanEntity", b =>
                {
                    b.Property<Guid>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_id");

                    b.Property<int>("Commission")
                        .HasColumnType("int")
                        .HasColumnName("commision");

                    b.Property<DateTime>("DisbursmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("disbursment_date");

                    b.Property<DateTime>("FirtsPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<int>("InteretRate")
                        .HasColumnType("int")
                        .HasColumnName("interes_rate");

                    b.Property<bool>("LoanAmount")
                        .HasColumnType("bit")
                        .HasColumnName("loan_amount");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_name");

                    b.HasKey("LoanId");

                    b.ToTable("loans", "dbo");
                });

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.AmortizationDataEntity", b =>
                {
                    b.HasOne("ExamenSegundaUnidad.Database.Entity.LoanEntity", "Loan")
                        .WithMany("Amortizations")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("ExamenSegundaUnidad.Database.Entity.LoanEntity", b =>
                {
                    b.Navigation("Amortizations");
                });
#pragma warning restore 612, 618
        }
    }
}
